### ISSUE TITLE
Descrition option required for ItemRequest when request type is HOLD

### ISSUE THREAD

**Issue by body-clock** [tulibraries/alma_rb#96]
In the `ItemRequest` class, `initialize` calls `super` on the parent class `BibRequest` which runs `validate!`. This runs the overridden `additional_validation!` method which fails with the following error: 
```ruby
      args.fetch(:description) do
        raise ArgumentError.new(
          ":description option must be specified when request_type is DIGITIZATION"
        )
      end
```
There is no check to ensure the holding type is NOT `DIGITIZATION`, so a request type of `HOLD` will fail without a provided `description` argument. We're trying to use the `ItemRequest` to make specific request for items using the `mms_id`, `holding_id`, and `item_pid`, but I don't think a `description` argument should be necessary for this to work. I could be missing something here, so please enlighten me if that's the case.

**Comment by ebtoner** [comment]
Thanks @body-clock for the PR! As mentioned in my comment on the PR, we're not 100% sure what the deal is with this validation Occassionally there are gaps in the API's documentation, so that could have been the case here for the digitization requests? Let us know if you run into any additional issues working on this.
